name: Deploy to Kyma

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    name: Deploy to Kyma
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to Kyma cluster
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          command: apply -f k8s/amcart-frontend-deployment.yaml
          
      - name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG }}
          command: rollout status deployment/amcart-frontend -n amcart-frontend
          
      - name: Output deployment URL
        run: |
          echo "Deployment successful! The application is available at:"
          echo "https://amcart-nagarro.c-418bb73.kyma.ondemand.com"